typography_spectrum: 0.8530879188328981
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.18334290431812406
  lightness: 0.7530446276068687
  saturation: 0.2985115246847272
  rhythmicContrast: 0.3008412946946919
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2526540805120021
analytics:
  google: null
  facebook: null
  twitter: null
name: cbrains2
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: LONG-TERM POTENTIATION
    id: bdd5d4f0-f8e3-4082-9fc7-04402dc7f717
    type: content
favicon: null
title: CBrains
description: Some brain stuff
purpose:
  - type: internal
    label: Long Term
    item: bdd5d4f0-f8e3-4082-9fc7-04402dc7f717
  - type: contact
    url: 'mailto:carl@connectedbrains.com'
    label: Contact me
