typography_spectrum: 0.918842145241797
style: the-composer
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.3125
  lightness: 0.44007928343489766
  saturation: 0.6098690463695675
  rhythmicContrast: 0.1544457117561251
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.63758
analytics:
  google: null
  facebook: null
  twitter: null
name: cbrains
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
