typography_spectrum: 0.8530879188328981
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.18334290431812406
  lightness: 0.7530446276068687
  saturation: 0.2985115246847272
  rhythmicContrast: 0.3008412946946919
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2526540805120021
analytics:
  google: null
  facebook: null
  twitter: null
name: cbrains
cta:
  domain: null
  bucket: null
  version: null
style: the-composer
favicon: null
purpose:
  - id: 01cead2c-4ecb-490c-a504-306f320972b1
    type: external
    value: www.connectedbrains.com
    label: CBrains
